[general]
import = [
"~/.config/alacritty/themes/rose-pine.toml",
]

[font]
size = 12.0

[font.normal]
family = "FantasqueSansMNerdFontMono"
style = "Regular"

[window]
dynamic_padding = true

[window.padding]
x = 8
y = 8

