#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
wmname LG3D

bspc monitor -d   󰭹 󰞇 \* 

bspc config border_width     4
bspc config window_gap      12
bspc config top_padding       0

bspc config normal_border_color "#191724"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Thorium-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Bitwarden desktop='^2' state=floating
bspc rule -a discord desktop='^3'
bspc rule -a Element desktop='^3'

# oldschool runescape
bspc rule -a BoltLauncher desktop='^4' state=floating
bspc rule -a net-runelite-client-RuneLite desktop=^4 state=floating
bspc rule -a net-runelite-launcher-Launcher desktop=^4 state=floating

